### ISSUE TITLE
V2 form feedback

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/mc2-dls-form#2]
Hey @Bankso - creating a PR seemed like more trouble than it's worth, so sharing feedback here:

## Before you begin

- [x] I'd maybe change "Projected" to "Tentative"
- [x] Resources are generated and _**ultimately**_ transferred to NIH-supported repositories (independently by generators or guided by the MC2 Center) _**or otherwise appropriate destinations compliant with the [NIH Data Management and Sharing Policy](https://sharing.nih.gov/data-management-and-sharing-policy)**_
- [x] Metadata describing the resource(s) are _**provided by generators and**_ captured by Sage Bionetworks according to standardized models agreed upon by the community
- [x] Sage Bionetworks stores metadata _**(and, as needed on a temporary or long term basis, data files)**_ using the secure [Synapse platform](https://www.synapse.org/) (I could take or leave this edit, if it feels potentially confusing)

## Project information

- [x] Maybe "Resource Coordinator" instead of "Data Coordinator" for consistency.
- [x] Hopefully they understand that the Point of Contact is for their project, but I don't see an obvious way to preemptively clarify...

## Resource information

- [x] ... and models _**(animal, tissue, cell line, etc.)**_ ("model" is a bit of a loaded term with the computational/mathematical folks in these communities)
(on closer inspection, it looks like you meant computational models — disregard this one)

## Datasets

- [x] We already discussed on Slack, but maybe as a reminder somewhere here clarify "type 'Other', 'Unsure', or 'Do not know' directly into any fields as applicable"

## Tools and computational models

- [x] I'd add a note at the top: "If you would like to share multiple components/interfaces for a tool (e.g., a web app, API service, and Python library), please add an entry for each Type."

**Comment by Bankso** [comment]
Thanks for writing all this up, @jaeddy! I think all of these changes make sense.
